#!/usr/bin/env bash
# Tests for conventional-commit-guard.sh. Run by hand: bash conventional-commit-guard.test.sh
# Feeds hook JSON on stdin and asserts on stdout. Exits non-zero on any failure.
set -u

HOOK="$(cd "$(dirname "$0")" && pwd)/conventional-commit-guard.sh"

# The guard reads the commit scope rule from soong.json. Without a pinned
# XDG_DATA_HOME the suite would read the developer's own config and the scope
# cases would pass or fail depending on whose machine ran them.
XDG_DATA_HOME="$(mktemp -d)" || { echo "cannot create a temp dir" >&2; exit 1; }
export XDG_DATA_HOME
trap 'rm -rf "$XDG_DATA_HOME"' EXIT

# The hook resolves its project key from git, so the suite needs a repo to sit
# in that is not the checkout it was launched from.
fixture="$XDG_DATA_HOME/repo"
git init -q "$fixture" 2>/dev/null
cd "$fixture" || { echo "cannot enter the fixture repo" >&2; exit 1; }
project="repo"

setup="$(cd "$(dirname "$HOOK")/../../skills/soong-setup/scripts" && pwd)/soong-setup.sh"

# Put the repo in one of the three scope states. No argument clears it.
scope_state() {
  if [ -n "${1:-}" ]; then
    bash "$setup" set --require-scope "$1" "$project" >/dev/null 2>&1
  else
    rm -f "$XDG_DATA_HOME/soong/soong.json"
  fi
}

pass=0
fail=0

# Build hook JSON the same way the harness does, so HEREDOC newlines survive.
run() {
  jq -Rs '{tool_input:{command:.}}' <<<"$1" | bash "$HOOK"
}

verdict() {
  local out
  out=$(run "$1")
  if [ -z "$out" ]; then
    printf 'silent'
  elif printf '%s' "$out" | jq -e '.hookSpecificOutput.permissionDecision == "deny"' >/dev/null 2>&1; then
    printf 'deny'
  elif printf '%s' "$out" | jq -e '.hookSpecificOutput.additionalContext' >/dev/null 2>&1; then
    printf 'advise'
  else
    printf 'malformed'
  fi
}

check() {
  local want="$1" desc="$2" cmd="$3" got
  got=$(verdict "$cmd")
  if [ "$got" = "$want" ]; then
    pass=$((pass + 1))
  else
    fail=$((fail + 1))
    printf 'FAIL  want=%-7s got=%-7s %s\n' "$want" "$got" "$desc"
  fi
}

# A comment command carrying $1 as its body.
comment_with() { printf 'gh pr comment 5 -b %s' "'$1'"; }

# --- signature pattern: deny rows -------------------------------------------
while IFS= read -r line; do
  [ -n "$line" ] || continue
  check deny "sig deny: $line" "$(comment_with "$line")"
done <<'EOF'
Addressed by Claude Code
🤖 Addressed by Claude Code
Fixed by Claude Code.
  Resolved with Claude
-- Generated by Claude Code
*Addressed by Claude Code*
_Addressed by Claude Code_
-- Addressed by Claude Code --
> Addressed by Claude Code
Addressed by Claude Code 🤖
— Addressed by Claude Code
Handled by Claude
EOF

# --- signature pattern: pass rows (advisory only) ---------------------------
while IFS= read -r line; do
  [ -n "$line" ] || continue
  check advise "sig pass: $line" "$(comment_with "$line")"
done <<'EOF'
Done. The hook is now invoked by Claude Code before every Bash call.
Skill files are read by Claude Code at session start
the check is performed by Claude Code hooks at PreToolUse
That case is handled by Claude Code hooks already.
Resolved with claude-flavoured tooling in mind, see docs.
addressed in abc123
this breaks under Claude Code 2.x
Fixed the parser so it handles HEREDOCs.
EOF

# --- trailer pattern --------------------------------------------------------
check deny   'trailer: co-authored-by' "$(comment_with 'Co-Authored-By: Claude <noreply@anthropic.com>')"
check deny   'trailer: bare emoji'     "$(comment_with '🤖')"
check deny   'trailer: -- emoji'       "$(comment_with '-- 🤖')"
check advise 'trailer prose: co-authored-by' "$(comment_with 'The co-authored-by trailer is stripped by the hook.')"
check advise 'trailer prose: emoji banned'   "$(comment_with 'The 🤖 emoji is banned in PR bodies, see the shared rules.')"
check advise 'trailer prose: emoji in test'  "$(comment_with 'Added a test asserting 🤖 is rejected.')"
check advise 'trailer prose: bot works'      "$(comment_with 'Nice, the bot works 🤖')"
# Regression for the unanchored emoji: a reply quoting the hook's own pattern.
check advise 'trailer prose: quotes grep pattern' \
  'gh pr comment 5 -b "grep -qiE \"generated with|co-authored-by|🤖\""'

# --- generated-with pattern -------------------------------------------------
# Must be tested in its LINKED form. Bare "Generated with Claude Code" denies via
# the signature pattern and would mask a missing generated-with check.
check deny   'genwith: canonical linked footer' \
  "$(comment_with '🤖 Generated with [Claude Code](https://claude.com/claude-code)')"
check deny   'genwith: bare'        "$(comment_with 'Generated with Claude Code')"
check deny   'genwith: non-claude'  "$(comment_with 'Generated with the manage-pr skill')"
check deny   'genwith: -- prefix'   "$(comment_with '-- Generated with Claude Code')"
check advise 'genwith prose: footer says' "$(comment_with 'The footer says "Generated with" and must be stripped.')"
check advise 'genwith prose: with care'   "$(comment_with 'This PR body was generated with care, see the note.')"

# --- multi-line bodies ------------------------------------------------------
check deny 'multiline: signature on its own last line' \
  "$(printf 'gh pr comment 5 -b %s' "'Tightened the regex per your note.

Addressed by Claude Code'")"
check advise 'multiline: verb then By-Claude sentence across lines' \
  "$(printf 'gh pr comment 5 -b %s' "'Done.
By Claude Code convention we skip this.'")"

# --- command matching, one case per family ---------------------------------
check deny   'family: gh pr comment'  "gh pr comment 5 -b 'Addressed by Claude Code'"
check deny   'family: gh pr review'   "gh pr review 5 --comment -b 'Addressed by Claude Code'"
check deny   'family: gh api replies' "gh api repos/o/r/pulls/1/comments/2/replies -f body='Addressed by Claude Code'"
check advise 'family: gh pr comment, clean body' "gh pr comment 5 -b 'Fixed the parser.'"
check advise 'family: gh pr comment --body-file' "gh pr comment 5 --body-file /tmp/reply.md"
check advise 'family: gh api POST method' "gh api repos/o/r/pulls/1/comments --method POST -f body='Fixed it.'"
check silent 'family: gh api read-only comments listing' "gh api repos/o/r/pulls/1/comments"
check silent 'family: gh api graphql reviewThreads' "gh api graphql -f query='reviewThreads'"
check silent 'family: gh pr view'    "gh pr view --json number,url"
check silent 'family: unrelated git' "git commit -m 'fix parser'"

# --- HEREDOC through real hook JSON ----------------------------------------
heredoc_cmd=$(cat <<'OUTER'
gh api repos/o/r/pulls/1/comments/2/replies -f body="$(cat <<'EOF'
Tightened the regex per your note.

Addressed by Claude Code
EOF
)"
OUTER
)
check deny 'heredoc: signature survives newlines into the hook' "$heredoc_cmd"

# --- branch 1: title rules -------------------------------------------------
# These rows are about title shape, not about setup, so the repo is configured
# throughout -- an unconfigured one is denied before any of it is reached. The
# scoped and unscoped rows are split because there is no longer a state that
# permits both: "no preference" now means "not set up yet".
scope_state true
check deny   'title: wildcard scope'   'gh pr create --title "feat(*): add new command" --body "x"'
check deny   'title: not conventional' 'gh pr create --title "add a new command" --body "x"'
check advise 'title: valid'            'gh pr create --title "feat(hooks): enforce PR conventions" --body "x"'
check advise 'title: multi-package scope' 'gh pr create --title "refactor(notifications,types): sync every property" --body "x"'
check deny   'title: whitespace in scope' 'gh pr create --title "feat(a b): add thing" --body "x"'
check deny   'title: empty scope segment' 'gh pr create --title "refactor(types,,schemas): sync every property" --body "x"'

# The scope cap: three areas is a cross-cutting change, four is a file list.
# Independent of the require_scope rule -- a repo that requires scopes still
# wants them to name something.
scope_state true
check advise 'cap: one segment'    'gh pr create --title "feat(hooks): thing"'
check advise 'cap: two segments'   'gh pr create --title "feat(hooks,polish): thing"'
check advise 'cap: three segments' 'gh pr create --title "feat(hooks,polish,manage-pr): thing"'
check deny   'cap: four segments'  'gh pr create --title "feat(a,b,c,d): thing"'
check deny   'cap: five segments'  'gh pr create --title "feat(a,b,c,d,e): thing"'

# The cap applies to commit subjects too, from the same shared function.
check deny 'cap: four on a commit' 'git commit -m "feat(a,b,c,d): thing"'

# The deny must say what to do, not merely that the title is wrong.
if run 'gh pr create --title "feat(a,b,c,d): thing"' \
   | jq -e '.hookSpecificOutput.permissionDecisionReason | test("at most three")' >/dev/null; then
  pass=$((pass + 1))
else
  fail=$((fail + 1))
  printf 'FAIL  scope cap deny did not state the limit\n'
fi

scope_state false
check deny   'title: footer in body'   'gh pr create --title "feat: add command" --body "Co-Authored-By: Claude"'
check advise 'title: valid no scope'   'gh pr create --title "fix: handle empty commit range" --body "x"'
# No scope, no segments, no spurious cap violation.
check advise 'cap: unscoped is zero'   'gh pr create --title "fix: thing"'

# Two simultaneous violations must join with "; " including the space.
two=$(run 'gh pr create --title "feat(*): add thing" --body "Generated with Claude Code"')
if printf '%s' "$two" | jq -r '.hookSpecificOutput.permissionDecisionReason' | grep -q '; '; then
  pass=$((pass + 1))
else
  fail=$((fail + 1))
  printf 'FAIL  two reasons not joined with "; "\n'
fi

# --- compound command: branch 1 wins, exactly one JSON object --------------
compound="gh pr edit 5 --body 'x' && gh pr comment 5 -b 'Addressed by Claude Code'"
objects=$(run "$compound" | jq -s 'length')
if [ "$objects" = "1" ]; then
  pass=$((pass + 1))
else
  fail=$((fail + 1))
  printf 'FAIL  compound emitted %s JSON objects, want 1\n' "$objects"
fi
# It must be branch 1's advisory, not branch 2's deny, confirming the ordering.
if run "$compound" | jq -e '.hookSpecificOutput.additionalContext | test("title format")' >/dev/null; then
  pass=$((pass + 1))
else
  fail=$((fail + 1))
  printf 'FAIL  compound did not stop at branch 1\n'
fi

# --- every branch emits valid JSON or nothing -----------------------------
for c in \
  'gh pr create --title "feat: x" --body "y"' \
  'gh pr create --title "nope" --body "y"' \
  "gh pr comment 5 -b 'Fixed it.'" \
  "gh pr comment 5 -b 'Addressed by Claude Code'" \
  'git commit -m "feat(api): thing"' \
  'git status'
do
  out=$(run "$c")
  if [ -z "$out" ] || printf '%s' "$out" | jq -e . >/dev/null 2>&1; then
    pass=$((pass + 1))
  else
    fail=$((fail + 1))
    printf 'FAIL  invalid JSON for: %s\n' "$c"
  fi
done

# --- the polish precondition ------------------------------------------------
# The guard denies a PR create/edit whose HEAD carries no Polish-passes trailer.
# These need real commits, and the main fixture is deliberately commit-less (it
# is what exercises the fail-open path above), so they run in a repo of their own
# and this one returns to the fixture afterwards.
polish_repo="$XDG_DATA_HOME/polish"
git init -q "$polish_repo" 2>/dev/null
git -C "$polish_repo" config user.email t@example.com
git -C "$polish_repo" config user.name t

# Configured, because an unconfigured repo is denied on that alone and these
# rows are about the trailer. Its project key is the directory name, "polish",
# not the fixture's.
bash "$setup" set --require-scope false polish >/dev/null 2>&1

# An unborn HEAD must fail open: unreadable is not the same as absent, and a
# guard that denies every PR in a fresh repo is worse than one that stops
# checking.
cd "$polish_repo" || exit 1
check advise 'polish: unborn HEAD falls open' 'gh pr create --title "feat: thing" --body "x"'

git commit -q --allow-empty -m "feat: work"
check deny   'polish: no trailer on HEAD'     'gh pr create --title "feat: thing" --body "x"'
check deny   'polish: no trailer on edit'     'gh pr edit 5 --title "feat: thing"'
check advise 'polish: --no-polish opts out'   'gh pr create --title "feat: thing" --body "x" --no-polish'

# The deny must name the trailer, so the reason tells the reader what to run
# rather than only that something is wrong.
if run 'gh pr create --title "feat: thing"' \
   | jq -e '.hookSpecificOutput.permissionDecisionReason | test("Polish-passes")' >/dev/null; then
  pass=$((pass + 1))
else
  fail=$((fail + 1))
  printf 'FAIL  polish deny did not name the trailer\n'
fi

# A correct title denied only on the trailer must NOT be told to fix the title.
# That tail belongs to the title and footer reasons; over a good title it sends
# the reader to edit something that was already right.
if run 'gh pr create --title "feat: thing" --body "x"' \
   | jq -e '.hookSpecificOutput.permissionDecisionReason
            | test("fix the title") | not' >/dev/null; then
  pass=$((pass + 1))
else
  fail=$((fail + 1))
  printf 'FAIL  polish-only deny told the reader to fix the title\n'
fi

# The opt-out rides as a trailing shell comment, because `gh` rejects it as an
# unknown flag. The hook reads the raw command string, so it still sees it.
check advise 'polish: comment-form opt-out' 'gh pr create --title "feat: thing" --body "x"  # --no-polish'

git commit -q --allow-empty -m "refactor: polish" -m "Polish-passes: review,simplify"
check advise 'polish: trailer on HEAD'        'gh pr create --title "feat: thing" --body "x"'

# Anchored on HEAD alone. A branch that polished and then committed more work is
# stale, and a range check would wrongly pass it -- the exact case the trailer
# check exists to catch.
git commit -q --allow-empty -m "feat: more work"
check deny   'polish: stale after new commit' 'gh pr create --title "feat: thing" --body "x"'

# A title problem and a missing trailer are both reported, not just the first.
git commit -q --allow-empty -m "feat: work"
if run 'gh pr create --title "nope"' \
   | jq -e '.hookSpecificOutput.permissionDecisionReason
            | test("Conventional Commits") and test("Polish-passes")' >/dev/null; then
  pass=$((pass + 1))
else
  fail=$((fail + 1))
  printf 'FAIL  polish deny did not combine with the title reason\n'
fi

# The precondition is a PR-branch rule only. A commit must not be judged on it,
# or polish could never make the commit that clears it.
# Never deny. This repo is configured, so the commit branch advises on its scope
# rule -- what matters is that the missing trailer plays no part in it, or polish
# could never make the commit that clears it.
check advise 'polish: commit unaffected'      'git commit -m "feat: thing"'

cd "$fixture" || exit 1

# The hook finds soong-setup.sh relative to its own path. A directory move must
# fail here rather than silently disabling the scope rule.
if [ -f "$setup" ]; then
  pass=$((pass + 1))
else
  fail=$((fail + 1))
  printf 'FAIL  soong-setup.sh not found at %s\n' "$setup"
fi

# --- scope rule on PR titles ------------------------------------------------
scope_state true
check deny   'scoped required, none given'   'gh pr create --title "feat: thing"'
check advise 'scoped required, one given'    'gh pr create --title "feat(api): thing"'
check deny   'scoped required, placeholder'  'gh pr create --title "feat(*): thing"'

scope_state false
check deny   'scope forbidden, one given'    'gh pr create --title "feat(api): thing"'
check advise 'scope forbidden, none given'   'gh pr create --title "feat: thing"'

# An unconfigured repo is denied, whatever the title. This used to be the
# permissive state -- both forms accepted, nothing enforced -- which meant the
# guard was decoration until someone remembered to run soong-setup. A rule that
# only works when it has been switched on is not a rule, so "not set up" is now
# a denial that names the fix.
scope_state
check deny 'unconfigured denies a scoped title'   'gh pr create --title "feat(api): thing"'
check deny 'unconfigured denies an unscoped one'  'gh pr create --title "feat: thing"'
check deny 'unconfigured denies a placeholder'    'gh pr create --title "feat(misc): thing"'
check deny 'unconfigured denies a bad shape'      'gh pr create --title "thing"'

# The denial must name soong-setup. A guard that refuses without saying what to
# run just looks broken.
if run 'gh pr create --title "feat(api): thing"' \
   | jq -e '.hookSpecificOutput.permissionDecisionReason | test("soong-setup")' >/dev/null; then
  pass=$((pass + 1))
else
  fail=$((fail + 1))
  printf 'FAIL  unconfigured deny did not name soong-setup\n'
fi

# a corrupt config must not enforce a scope rule, and must not break the guard
mkdir -p "$XDG_DATA_HOME/soong"
printf 'not json' > "$XDG_DATA_HOME/soong/soong.json"
check advise 'corrupt config falls open'     'gh pr create --title "feat: thing"'
check deny   'corrupt config still checks shape' 'gh pr create --title "thing"'
scope_state

# --- commit subjects --------------------------------------------------------
# The whole branch is gated on the commits capability. An unconfigured repo hears
# nothing at all, including on shape, because commits are far higher-frequency
# than PR titles and a new universal denial on them is the more damaging one.
scope_state
check silent 'unset ignores a bad commit'  'git commit -m "wip"'
check silent 'unset ignores a good commit' 'git commit -m "feat(api): thing"'

scope_state true
check deny   'commit needs a scope'        'git commit -m "feat: thing"'
check advise 'commit has a scope'          'git commit -m "feat(api): thing"'
check deny   'commit shape is checked'     'git commit -m "wip"'

scope_state false
check deny   'commit must not be scoped'   'git commit -m "feat(api): thing"'
check advise 'commit is unscoped'          'git commit -m "feat: thing"'

# a Co-Authored-By trailer is required by CLAUDE.md, so it must stay legal
scope_state true
check advise 'trailer is allowed' 'git commit -m "feat(api): thing" -m "Co-Authored-By: Claude Opus 5 <noreply@anthropic.com>"'

# the first -m is the subject; later ones are body paragraphs
check advise 'later -m is not the subject' 'git commit -m "feat(api): thing" -m "wip notes"'

# messages the hook cannot read: advise, never deny
check advise 'no -m at all'   'git commit'
check advise 'message in a file' 'git commit -F /tmp/msg'
check advise 'amend without -m'  'git commit --amend --no-edit'

# git generates these subjects and a later rebase absorbs them
check advise 'fixup is exempt'  'git commit --fixup=HEAD'
check advise 'squash is exempt' 'git commit --squash=HEAD'

# the PR branch is ordered first, so a compound command stops there
check deny 'compound stops at the PR title' 'git commit -m "feat(api): ok" && gh pr create --title "bad"'
scope_state

# --- the scope-rule read is lazy -------------------------------------------
# This hook runs on every Bash call, so reading the config unconditionally costs
# every unrelated command three processes. Guard that by counting the reads
# instead of timing them: copy the hook into a fake plugin tree whose
# $0-relative soong-setup.sh is a wrapper that appends a line per invocation,
# then assert the log is empty for a command no branch cares about and non-empty
# for a PR title. A timing assertion would be flaky; a call count is exact.
lazy_root="$XDG_DATA_HOME/lazy"
mkdir -p "$lazy_root/hooks/scripts" "$lazy_root/skills/soong-setup/scripts"
cp "$HOOK" "$lazy_root/hooks/scripts/conventional-commit-guard.sh"
calls="$lazy_root/calls.log"
cat > "$lazy_root/skills/soong-setup/scripts/soong-setup.sh" <<EOF
#!/usr/bin/env bash
printf 'call\n' >> "$calls"
exec bash "$setup" "\$@"
EOF

# Count the reads one command makes, via the recording copy of the hook.
read_count() {
  : > "$calls"
  jq -Rs '{tool_input:{command:.}}' <<<"$1" \
    | bash "$lazy_root/hooks/scripts/conventional-commit-guard.sh" >/dev/null 2>&1
  # No log file at all is zero reads, not an error.
  [ -f "$calls" ] && wc -l < "$calls" | tr -d ' ' || printf '0'
}

# A command reaching no branch that needs the rule must not read the config.
got=$(read_count 'ls')
if [ "$got" = "0" ]; then
  pass=$((pass + 1))
else
  fail=$((fail + 1))
  printf 'FAIL  lazy: ls read the scope config %s times, want 0\n' "$got"
fi

# The PR-title branch must read it, and memoization means exactly once.
got=$(read_count 'gh pr create --title "feat(api): thing"')
if [ "$got" = "1" ]; then
  pass=$((pass + 1))
else
  fail=$((fail + 1))
  printf 'FAIL  lazy: gh pr create read the scope config %s times, want 1\n' "$got"
fi

printf '\n%s passed, %s failed\n' "$pass" "$fail"
[ "$fail" -eq 0 ]
