#!/usr/bin/env bash
# Tests for pr-guard.sh. Run by hand: bash pr-guard.test.sh
# Feeds hook JSON on stdin and asserts on stdout. Exits non-zero on any failure.
set -u

HOOK="$(cd "$(dirname "$0")" && pwd)/pr-guard.sh"

# pr-guard reads the commit scope rule from soong.json. Without a pinned
# XDG_DATA_HOME the suite would read the developer's own config and the scope
# cases would pass or fail depending on whose machine ran them.
XDG_DATA_HOME="$(mktemp -d)" || { echo "cannot create a temp dir" >&2; exit 1; }
export XDG_DATA_HOME
trap 'rm -rf "$XDG_DATA_HOME"' EXIT

# The hook resolves its project key from git, so the suite needs a repo to sit
# in that is not the checkout it was launched from.
fixture="$XDG_DATA_HOME/repo"
git init -q "$fixture" 2>/dev/null
cd "$fixture" || { echo "cannot enter the fixture repo" >&2; exit 1; }
project="repo"

setup="$(cd "$(dirname "$HOOK")/../../skills/soong-setup/scripts" && pwd)/soong-setup.sh"

# Put the repo in one of the three scope states. No argument clears it.
scope_state() {
  if [ -n "${1:-}" ]; then
    bash "$setup" set --require-scope "$1" "$project" >/dev/null 2>&1
  else
    rm -f "$XDG_DATA_HOME/soong/soong.json"
  fi
}

pass=0
fail=0

# Build hook JSON the same way the harness does, so HEREDOC newlines survive.
run() {
  jq -Rs '{tool_input:{command:.}}' <<<"$1" | bash "$HOOK"
}

verdict() {
  local out
  out=$(run "$1")
  if [ -z "$out" ]; then
    printf 'silent'
  elif printf '%s' "$out" | jq -e '.hookSpecificOutput.permissionDecision == "deny"' >/dev/null 2>&1; then
    printf 'deny'
  elif printf '%s' "$out" | jq -e '.hookSpecificOutput.additionalContext' >/dev/null 2>&1; then
    printf 'advise'
  else
    printf 'malformed'
  fi
}

check() {
  local want="$1" desc="$2" cmd="$3" got
  got=$(verdict "$cmd")
  if [ "$got" = "$want" ]; then
    pass=$((pass + 1))
  else
    fail=$((fail + 1))
    printf 'FAIL  want=%-7s got=%-7s %s\n' "$want" "$got" "$desc"
  fi
}

# A comment command carrying $1 as its body.
comment_with() { printf 'gh pr comment 5 -b %s' "'$1'"; }

# --- signature pattern: deny rows -------------------------------------------
while IFS= read -r line; do
  [ -n "$line" ] || continue
  check deny "sig deny: $line" "$(comment_with "$line")"
done <<'EOF'
Addressed by Claude Code
🤖 Addressed by Claude Code
Fixed by Claude Code.
  Resolved with Claude
-- Generated by Claude Code
*Addressed by Claude Code*
_Addressed by Claude Code_
-- Addressed by Claude Code --
> Addressed by Claude Code
Addressed by Claude Code 🤖
— Addressed by Claude Code
Handled by Claude
EOF

# --- signature pattern: pass rows (advisory only) ---------------------------
while IFS= read -r line; do
  [ -n "$line" ] || continue
  check advise "sig pass: $line" "$(comment_with "$line")"
done <<'EOF'
Done. The hook is now invoked by Claude Code before every Bash call.
Skill files are read by Claude Code at session start
the check is performed by Claude Code hooks at PreToolUse
That case is handled by Claude Code hooks already.
Resolved with claude-flavoured tooling in mind, see docs.
addressed in abc123
this breaks under Claude Code 2.x
Fixed the parser so it handles HEREDOCs.
EOF

# --- trailer pattern --------------------------------------------------------
check deny   'trailer: co-authored-by' "$(comment_with 'Co-Authored-By: Claude <noreply@anthropic.com>')"
check deny   'trailer: bare emoji'     "$(comment_with '🤖')"
check deny   'trailer: -- emoji'       "$(comment_with '-- 🤖')"
check advise 'trailer prose: co-authored-by' "$(comment_with 'The co-authored-by trailer is stripped by the hook.')"
check advise 'trailer prose: emoji banned'   "$(comment_with 'The 🤖 emoji is banned in PR bodies, see the shared rules.')"
check advise 'trailer prose: emoji in test'  "$(comment_with 'Added a test asserting 🤖 is rejected.')"
check advise 'trailer prose: bot works'      "$(comment_with 'Nice, the bot works 🤖')"
# Regression for the unanchored emoji: a reply quoting the hook's own pattern.
check advise 'trailer prose: quotes grep pattern' \
  'gh pr comment 5 -b "grep -qiE \"generated with|co-authored-by|🤖\""'

# --- generated-with pattern -------------------------------------------------
# Must be tested in its LINKED form. Bare "Generated with Claude Code" denies via
# the signature pattern and would mask a missing generated-with check.
check deny   'genwith: canonical linked footer' \
  "$(comment_with '🤖 Generated with [Claude Code](https://claude.com/claude-code)')"
check deny   'genwith: bare'        "$(comment_with 'Generated with Claude Code')"
check deny   'genwith: non-claude'  "$(comment_with 'Generated with the manage-pr skill')"
check deny   'genwith: -- prefix'   "$(comment_with '-- Generated with Claude Code')"
check advise 'genwith prose: footer says' "$(comment_with 'The footer says "Generated with" and must be stripped.')"
check advise 'genwith prose: with care'   "$(comment_with 'This PR body was generated with care, see the note.')"

# --- multi-line bodies ------------------------------------------------------
check deny 'multiline: signature on its own last line' \
  "$(printf 'gh pr comment 5 -b %s' "'Tightened the regex per your note.

Addressed by Claude Code'")"
check advise 'multiline: verb then By-Claude sentence across lines' \
  "$(printf 'gh pr comment 5 -b %s' "'Done.
By Claude Code convention we skip this.'")"

# --- command matching, one case per family ---------------------------------
check deny   'family: gh pr comment'  "gh pr comment 5 -b 'Addressed by Claude Code'"
check deny   'family: gh pr review'   "gh pr review 5 --comment -b 'Addressed by Claude Code'"
check deny   'family: gh api replies' "gh api repos/o/r/pulls/1/comments/2/replies -f body='Addressed by Claude Code'"
check advise 'family: gh pr comment, clean body' "gh pr comment 5 -b 'Fixed the parser.'"
check advise 'family: gh pr comment --body-file' "gh pr comment 5 --body-file /tmp/reply.md"
check advise 'family: gh api POST method' "gh api repos/o/r/pulls/1/comments --method POST -f body='Fixed it.'"
check silent 'family: gh api read-only comments listing' "gh api repos/o/r/pulls/1/comments"
check silent 'family: gh api graphql reviewThreads' "gh api graphql -f query='reviewThreads'"
check silent 'family: gh pr view'    "gh pr view --json number,url"
check silent 'family: unrelated git' "git commit -m 'fix parser'"

# --- HEREDOC through real hook JSON ----------------------------------------
heredoc_cmd=$(cat <<'OUTER'
gh api repos/o/r/pulls/1/comments/2/replies -f body="$(cat <<'EOF'
Tightened the regex per your note.

Addressed by Claude Code
EOF
)"
OUTER
)
check deny 'heredoc: signature survives newlines into the hook' "$heredoc_cmd"

# --- branch 1: title rules -------------------------------------------------
check deny   'title: wildcard scope'   'gh pr create --title "feat(*): add new command" --body "x"'
check deny   'title: not conventional' 'gh pr create --title "add a new command" --body "x"'
check deny   'title: footer in body'   'gh pr create --title "feat: add command" --body "Co-Authored-By: Claude"'
check advise 'title: valid'            'gh pr create --title "feat(hooks): enforce PR conventions" --body "x"'
check advise 'title: valid no scope'   'gh pr create --title "fix: handle empty commit range" --body "x"'
check advise 'title: multi-package scope' 'gh pr create --title "refactor(notifications,types,schemas): sync every property" --body "x"'
check deny   'title: whitespace in scope' 'gh pr create --title "feat(a b): add thing" --body "x"'
check deny   'title: empty scope segment' 'gh pr create --title "refactor(types,,schemas): sync every property" --body "x"'

# Two simultaneous violations must join with "; " including the space.
two=$(run 'gh pr create --title "feat(*): add thing" --body "Generated with Claude Code"')
if printf '%s' "$two" | jq -r '.hookSpecificOutput.permissionDecisionReason' | grep -q '; '; then
  pass=$((pass + 1))
else
  fail=$((fail + 1))
  printf 'FAIL  two reasons not joined with "; "\n'
fi

# --- compound command: branch 1 wins, exactly one JSON object --------------
compound="gh pr edit 5 --body 'x' && gh pr comment 5 -b 'Addressed by Claude Code'"
objects=$(run "$compound" | jq -s 'length')
if [ "$objects" = "1" ]; then
  pass=$((pass + 1))
else
  fail=$((fail + 1))
  printf 'FAIL  compound emitted %s JSON objects, want 1\n' "$objects"
fi
# It must be branch 1's advisory, not branch 2's deny, confirming the ordering.
if run "$compound" | jq -e '.hookSpecificOutput.additionalContext | test("title format")' >/dev/null; then
  pass=$((pass + 1))
else
  fail=$((fail + 1))
  printf 'FAIL  compound did not stop at branch 1\n'
fi

# --- every branch emits valid JSON or nothing -----------------------------
for c in \
  'gh pr create --title "feat: x" --body "y"' \
  'gh pr create --title "nope" --body "y"' \
  "gh pr comment 5 -b 'Fixed it.'" \
  "gh pr comment 5 -b 'Addressed by Claude Code'" \
  'git status'
do
  out=$(run "$c")
  if [ -z "$out" ] || printf '%s' "$out" | jq -e . >/dev/null 2>&1; then
    pass=$((pass + 1))
  else
    fail=$((fail + 1))
    printf 'FAIL  invalid JSON for: %s\n' "$c"
  fi
done

# The hook finds soong-setup.sh relative to its own path. A directory move must
# fail here rather than silently disabling the scope rule.
if [ -f "$setup" ]; then
  pass=$((pass + 1))
else
  fail=$((fail + 1))
  printf 'FAIL  soong-setup.sh not found at %s\n' "$setup"
fi

# --- scope rule on PR titles ------------------------------------------------
scope_state true
check deny   'scoped required, none given'   'gh pr create --title "feat: thing"'
check advise 'scoped required, one given'    'gh pr create --title "feat(api): thing"'
check deny   'scoped required, placeholder'  'gh pr create --title "feat(*): thing"'

scope_state false
check deny   'scope forbidden, one given'    'gh pr create --title "feat(api): thing"'
check advise 'scope forbidden, none given'   'gh pr create --title "feat: thing"'

scope_state
check advise 'unset allows a scope'          'gh pr create --title "feat(api): thing"'
check advise 'unset allows no scope'         'gh pr create --title "feat: thing"'
check deny   'unset still denies placeholder' 'gh pr create --title "feat(misc): thing"'
check deny   'unset still denies bad shape'  'gh pr create --title "thing"'

# a corrupt config must not enforce a scope rule, and must not break the guard
mkdir -p "$XDG_DATA_HOME/soong"
printf 'not json' > "$XDG_DATA_HOME/soong/soong.json"
check advise 'corrupt config falls open'     'gh pr create --title "feat: thing"'
check deny   'corrupt config still checks shape' 'gh pr create --title "thing"'
scope_state

printf '\n%s passed, %s failed\n' "$pass" "$fail"
[ "$fail" -eq 0 ]
